import type { Metadata } from "next";
import { Montserrat as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/shared/ui/utils";
import { Providers } from "@/app/providers";
import UINavbar from "@/shared/ui/layout/ui-navbar";
import UIFooter from "@/shared/ui/layout/ui-footer";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased dark",
          fontSans.variable,
        )}
      >
        <Providers>
          <div className="flex min-h-screen flex-col">
            <UINavbar />
            <div className="grow">{children}</div>
            <UIFooter />
          </div>
        </Providers>
      </body>
    </html>
  );
}
